name: twobriefcases
favicon: null
layout_spectrum: 0.03966320212930441
typography_spectrum: 0.7088563900906593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7731219462584704
  lightness: 0.36577788228169084
  saturation: 0.902142810402438
  rhythmicContrast: 0.7257967407349497
purpose: []
